### ISSUE TITLE
[FEATURE] Add Haskell language option 

### ISSUE THREAD

**Issue by tusharxoxoxo** [codicocodes/speedtyper.dev#167]

**Comment by tusharxoxoxo** [comment]
@codicocodes When I was trying to set up this project locally, I am having trouble while connecting to the database
![image](https://github.com/codicocodes/speedtyper.dev/assets/79051850/12fca501-f011-4189-851e-ce4bc82252b6)
![image](https://github.com/codicocodes/speedtyper.dev/assets/79051850/3d3cfe26-0618-4e5b-823b-b8cfe05042c0)

**Comment by tusharxoxoxo** [comment]
`make run-seed-codesources
yarn --cwd ./packages/back-nest command seed-challenges
yarn run v1.22.19
$ TS_NODE_PROJECT=./tsconfig.json ts-node -r tsconfig-paths/register ./src/commands.ts seed-challenges
[Nest] 60969  - 01/21/2024, 1:15:44 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
error: database "speedtyper" does not exist
    at Parser.parseErrorMessage (/Users/blouse_man/Downloads/coding/github/speedtyper.dev/packages/back-nest/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/blouse_man/Downloads/coding/github/speedtyper.dev/packages/back-nest/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/blouse_man/Downloads/coding/github/speedtyper.dev/packages/back-nest/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/blouse_man/Downloads/coding/github/speedtyper.dev/packages/back-nest/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`

**Comment by tusharxoxoxo** [comment]
what are the things that need to be done to add ocaml language option?
By performing all the changes performed in this pr #151, will be enough to add ocaml language support to speedtyper, or some additional changes need to be done?

**Comment by tusharxoxoxo** [comment]
https://github.com/azolotko/speedtyper.dev/blob/87089a0412dc9e2b0f10cb40d4a3559638cd17f0/packages/back-nest/tracked-projects.txt

in this file, the source of the code is written from where the typing code is sourced which is shown at the bottom right corner on the website

i want to source the ocaml code from ocaml/dune, so how could i do it
