### ISSUE TITLE
Contributor introduction: database "speedtyper" does not exist

### ISSUE THREAD

**Issue by paeifbnaeufbpae** [codicocodes/speedtyper.dev#170]
I followed the contributor introduction step by step, and ran into errors. First, there was some error about `GITHUB_ACCESS_TOKEN` not being found, so I created one and set that environment value. (This should probably also be documented though.)

The next thing I'm running into is this:
```
~/speedtyper.dev $ make run-seed-codesources
yarn --cwd ./packages/back-nest command seed-challenges
yarn run v1.22.21
$ TS_NODE_PROJECT=./tsconfig.json ts-node -r tsconfig-paths/register ./src/commands.ts seed-challenges
[Nest] 46018  - 03/08/2024, 12:38:00 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
error: database "speedtyper" does not exist
    at Parser.parseErrorMessage (/Users/leontepe/speedtyper.dev/packages/back-nest/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/leontepe/speedtyper.dev/packages/back-nest/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/leontepe/speedtyper.dev/packages/back-nest/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/leontepe/speedtyper.dev/packages/back-nest/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Socket.Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
^Cmake: *** [run-seed-codesources] Interrupt: 2
```

So essentially just the database not existing. This, too, is not documented in the contributor introduction.

Of course it's possible to figure this out and solve this on your own, but I think that defeats the purpose of a contributor introduction. It should get you to a working initial state, where you can start fiddling around with things.

**Comment by paeifbnaeufbpae** [comment]
For reference, what I ended up doing:
1. Install PostgreSQL
2. Run `psql postgres` to enter the Postgres shell
3. Run `CREATE DATABASE speedtyper;` to create the database `speedtyper`
4. Run `CREATE ROLE speedtyper LOGIN;` to create the role `speedtyper` with login permissions
5. Run `CREATE ROLE postgres LOGIN;` to create the role `postgres` with login permissions
6. Run `ALTER ROLE postgres WITH SUPERUSER;` to give superuser permissions to the user `postgres` (you could probably be more fine-grained here, but this works, so...)

And that's it, if I remember correctly. Then `make run-seed-codesources` successfully runs.
