### ISSUE TITLE
Fix runtime exception

### ISSUE THREAD

**Issue by codicocodes** [codicocodes/speedtyper.dev#47]
The specific exception could be solved by using optional chaining syntax. However, you should not be able to send a backSpacePress when nextIndex is 0.

Id rather fix the undelrying bug if possible. Could be a racecondition here, that the event is from a previous match but the state has reloaded. This could potentially lead to a weird state? 

```
/app/dist/src/UserRaceState.js:140
if (!challenge.chars[nextIndex].skipped) {
^
TypeError: Cannot read properties of undefined (reading 'skipped')
at UserRaceState.findPreviousIndex (/app/dist/src/UserRaceState.js:140:45)
at UserRaceState.onBackspacePress (/app/dist/src/UserRaceState.js:270:27)
at Race.onBackspacePress (/app/dist/src/Race.js:196:80)
at RaceManager.onBackspacePress (/app/dist/src/RaceManager.js:160:58)
at Socket.backspacePressHandler (/app/dist/src/sockets/index.js:15:53)
at Socket.emit (node:events:513:28)
at /app/node_modules/socket.io/lib/socket.js:531:14
at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by codicocodes** [comment]
:information_source: Merged a quick fix. But still want to address the underlying problem.

Will probably break out another ticket to refactor the state management with unit testing.
